"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-14 20:59:39.862285
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('chars', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('call_status', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_call_uuid', sa.String(length=64), nullable=True),
    sa.Column('qualification', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.String(length=64), nullable=True),
    sa.Column('meeting_at', sa.String(length=64), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_call_status'), ['call_status'], unique=False)
        batch_op.create_index('ix_leads_dial_queue', ['status', 'call_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_meeting_at'), ['meeting_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_qualification'), ['qualification'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=True),
    sa.Column('to_number', sa.String(length=32), nullable=True),
    sa.Column('request_uuid', sa.String(length=64), nullable=True),
    sa.Column('call_uuid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hangup_cause', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('qualification', sa.String(length=32), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_call_uuid'), ['call_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_request_uuid'), ['request_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_events_call_id'))

    op.drop_table('events')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_status'))
        batch_op.drop_index(batch_op.f('ix_calls_session_id'))
        batch_op.drop_index(batch_op.f('ix_calls_request_uuid'))
        batch_op.drop_index(batch_op.f('ix_calls_lead_id'))
        batch_op.drop_index(batch_op.f('ix_calls_created_at'))
        batch_op.drop_index(batch_op.f('ix_calls_call_uuid'))

    op.drop_table('calls')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_qualification'))
        batch_op.drop_index(batch_op.f('ix_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_leads_meeting_at'))
        batch_op.drop_index('ix_leads_dial_queue')
        batch_op.drop_index(batch_op.f('ix_leads_call_status'))

    op.drop_table('leads')
    op.drop_table('documents')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
