"""multi_agent

Revision ID: 868a71b832bb
Revises: 0001
Create Date: 2026-09-15 00:08:53.670369
"""
from alembic import op
import sqlalchemy as sa


revision = '868a71b832bb'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('voice_speaker', sa.String(length=64), nullable=True),
    sa.Column('default_language', sa.String(length=16), nullable=True),
    sa.Column('prompt_objective', sa.Text(), nullable=True),
    sa.Column('prompt_instructions', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_calls_agent_id'), ['agent_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_agent_id'), ['agent_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_agent_id'), ['agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_agent_id'))
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_agent_id'))
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_agent_id'))
        batch_op.drop_column('agent_id')

    op.drop_table('agents')
    # ### end Alembic commands ###
