"""
Re-tag email events written before send_email carried an `actor`.

Every email was recorded with the default actor "system", so the Email Centre counted them all as
system reports ("AI emails 0, Manual 0"). New sends set the actor at the call site; this fixes history.

    python scripts/reclassify_email_events.py            # show what would change
    python scripts/reclassify_email_events.py --apply    # write it
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.database import SessionLocal
from app.models.event import Event

SYSTEM_MARKERS = ("voice agent daily report", "missed call:", "meeting reminder", "reminder:")


def classify(title: str, lead_id) -> str:
    text = (title or "").lower()
    if any(m in text for m in SYSTEM_MARKERS):
        return "system"
    # Everything else addressed to a lead was generated by the agent after a call.
    return "ai" if lead_id else "system"


def main(apply: bool):
    with SessionLocal() as db:
        events = db.query(Event).filter(Event.type == "email").all()
        changed = 0
        for e in events:
            want = classify(e.title, e.lead_id)
            if want != e.actor:
                print(f"{e.id}\t{e.actor} -> {want}\t{e.title[:70]}")
                changed += 1
                if apply:
                    e.actor = want
        if apply:
            db.commit()
        print(f"\n{changed} of {len(events)} email event(s) re-tagged.")
        print("Done." if apply else "Dry run: pass --apply to write.")


if __name__ == "__main__":
    main("--apply" in sys.argv)
